# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'LetsMeet' do
  use_frameworks!
  
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'

  pod 'Gallery'

  pod 'NVActivityIndicatorView/AppExtension'
  pod 'ProgressHUD'
  pod 'SKPhotoBrowser'
  pod 'Shuffle-iOS'

  pod 'MessageKit'
  pod 'InputBarAccessoryView'
  

  # Pods for LetsMeet

end
